# Generated by Django 6.0.7 on 2026-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('battingStyle', models.CharField(max_length=30)),
                ('bowlingStyle', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('runScored', models.IntegerField()),
                ('wicketsTaken', models.IntegerField()),
            ],
        ),
    ]
